# H2 in-memory database configuration for local development
spring.datasource.url=jdbc:h2:mem:devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# postgresql configuration for local development 
#spring.datasource.url=jdbc:postgresql://localhost:5432/chess_repertoire
#spring.datasource.username=postgres
#spring.datasource.password=admin

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.h2.console.enabled=false
